version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-app
    restart: always
    volumes:
      - .:/var/www
    working_dir: /var/www
  nginx:
    container_name: php-nginx
    image: nginx:1.19-alpine
    ports:
      - "8000:80"
    restart: always
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d